repos:
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: npm run lint:check
        language: node
        files: \.(ts|tsx)$
        pass_filenames: false
      - id: prettier
        name: Prettier
        entry: npm run format:check
        language: node
        files: \.(ts|tsx|json|css)$
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
